global:
  scrape_interval: 1m
  evaluation_interval: 1m
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
rule_files:
  - "rules_*.yml"


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

remote_write:
  - url: "http://metricbeat:9201/write"
