groups:
  - name: ExporterDown
    rules:
    - alert: ExporterDown
      expr: up == 0
      for: 0s
      labels:
        severity: warning
      annotations:
        summary: "Exporter down (instance {{ $labels.instance }})"
        description: "Prometheus exporter down\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

